Add /me endpoint that returns user's info
BD2KGenomics/dcc-dashboard pull request #59
Opened 2018-09-07 23:06 UTC by jessebrennan

This adds the '/me' endpoint and returns the requested info. Is there any security risk in giving back the access token in json @coverbeck?

2018-09-07 23:26 UTC, coverbeck commented
> Is there any security risk in giving back the access token in json @coverbeck?

I don't think so. There is a requirement to surface the token in the UI, DataBiosphere/cgp-boardwalk/65, so I think we have to return it.

Also, since we only support https, the body is not visible.

BTW, the access token already is in the cookie, as you know, and not encrypted, so this offers the same level of safety/danger as that.

2018-09-07 23:31 UTC, jessebrennan commented
> BTW, the access token already is in the cookie, as you know, and not encrypted, so this offers the same level of safety/danger as that.

Oh yeah. duh.

2018-09-07 23:40 UTC, coverbeck requested changes
I realize some of the comment changes may be my fault, as I may have written up incorrectly, but reading it again, I think they should be updated.

Looks good in general though! Nice and small set of changes.

2018-09-07 23:40 UTC, coverbeck commented on app.py
> +    """
Solid comments! Makes is easy to follow.

2018-09-07 23:40 UTC, coverbeck commented on app.py
> +    If authentication is enabled for the deployment, and there is no
This should be `required for the deployment` -- even if authentication is not required, we will still allow users to optionally log in.

2018-09-07 23:40 UTC, coverbeck commented on app.py
> +    If authentication is not enabled for the deployment, and there is no
required not enabled

2018-09-07 23:40 UTC, coverbeck commented on app.py
> +        return 'Invalid access code could not be refreshed', 401
1. It's an invalid (expired) refresh token, isn't it? Should you say the refresh token has expired?
2. I'm wondering if you shouldn't clear the refresh token from this cookie at this point, although I suppose there's the possibility that the request failed, for example, because the network connection was down or some unexpected situation. That's why I'm wondering if you can tell how it failed.

2018-09-07 23:40 UTC, coverbeck commented on app.py
> +    current_user.access_token = resp['access_token']
What happens if this call fails? Does it raise an exception, or do you need to check for it here first?

2018-09-10 17:24 UTC, jessebrennan commented on app.py
> +    If authentication is enabled for the deployment, and there is no
fixed

2018-09-10 17:24 UTC, jessebrennan commented on app.py
> +    If authentication is not enabled for the deployment, and there is no
fixed

2018-09-10 17:28 UTC, jessebrennan commented on app.py
> +        return 'Invalid access code could not be refreshed', 401
Yeah, I wasn't completely sure what to do here. If the token is invalid we get a 401.  Other responses I'm not sure about. I could pass it on the error if it's not 401. 

Otherwise you suggest clearing the token? Then prompting them to log back in again? We should discuss further.

2018-09-10 17:31 UTC, jessebrennan commented on app.py
> +    current_user.access_token = resp['access_token']
Sure I suppose if it failed it would raise an exception, but I don't see why it ever would.

2018-09-10 18:27 UTC, coverbeck commented on app.py
> +    current_user.access_token = resp['access_token']
It could fail because:

1. The refresh token could have expired
2. The refresh token could have been revoked (this should actually be a testable case, as you need to revoke the refresh token on logout)
3. Vague system issues -- even services like Google have outages, network connections fail or get saturated, etc.

2018-09-10 18:55 UTC, jessebrennan commented on app.py
> +    current_user.access_token = resp['access_token']
Oh I see, I thought you were referring to that specific line. Yeah I can document and make the usage more robust.

2018-09-10 19:00 UTC, coverbeck commented on app.py
> +        return 'Invalid access code could not be refreshed', 401
Minor point, I don't think you should say `access code`, I think you should `access token`.  I also think this is worth logging.

If it's an invalid token and not refreshable, then I think you should  clear both tokens. Returning 401 is enough; because this will be called via AJAX, you can't redirect to login from here.

The exceptions to clearing could be if you got 5xx from Google, which indicates an error on their side.

2018-09-10 19:02 UTC, coverbeck commented on app.py
> +    current_user.access_token = resp['access_token']
Ah, I see -- yes, I meant you may need error handling between lines 265 and 266.

2018-09-10 20:02 UTC, jessebrennan commented on app.py
> +    current_user.access_token = resp['access_token']
Actually, looking at the oauth.refresh_token code, if it fails to get a new token, it just returns the old token. So I'll just have to check for that case in the code that calls this function.

2018-09-10 22:47 UTC, coverbeck requested changes

2018-09-10 22:47 UTC, coverbeck commented on app.py
> +    output = dict((k, user_data[k]) for k in ('name', 'email'))
I was looking at this one last time, and I realized I overlooked this in my first review -- I think you should check against the whitelist if there is one.

One could argue that you could only have gotten here if you were on the whitelist in the first place, and that's true, but if somebody logged in, then got taken off the whitelist, they would still have access. So I think you should check.

The check may overlap with the work you are doing for the auth endpoint, so if you want to tackle it there instead, that would be OK (although maybe add a comment here saying you need to authorize).

2018-09-10 22:47 UTC, coverbeck commented on app.py
> +        return 'Failed to get user info: ' + resp.text, 401
I wonder if you should pop the access and refresh tokens here as well, like you do a few lines above?

I guess it depends what other status codes you can get on line 365... If the token is invalid, are you always going to get a 400?

2018-09-10 23:58 UTC, jessebrennan commented on app.py
> +        return 'Failed to get user info: ' + resp.text, 401
I was thinking against popping it again in case It's a 500 error. I'm not really sure what's possible but I figured if something unforeseen goes wrong this will catch it, pass the error on. 

If the token is invalid you should get a 400 error.

2018-09-10 23:59 UTC, jessebrennan commented on app.py
> +    output = dict((k, user_data[k]) for k in ('name', 'email'))
I was working on the auth endpoint on a sub-branch of this branch. I may just close this PR and reopen both changes together. The auth endpoint is requiring some refactoring of this stuff anyway.

2018-09-11 00:31 UTC, coverbeck commented on app.py
> +        return 'Failed to get user info: ' + resp.text, 401
I agree, you shouldn't pop it if it's a 5xx error -- that indicates some problem on the Google side that might get fixed by them. So if those are the only two types of status codes this is OK. Maybe add a comment though, since it wasn't clear to me, and won't necessarily be to the next person who reads it.

2018-09-11 00:31 UTC, coverbeck commented on app.py
> +    output = dict((k, user_data[k]) for k in ('name', 'email'))
Sounds good

2018-09-11 16:44 UTC, jessebrennan commented on app.py
> +        return 'Failed to get user info: ' + resp.text, 401
It may be a 500 error, but idk if it's possible there will be an other type of error. I can still add a comment to clarify though. Should I pop for any breed of 4xx errors (other than 400)?

2018-09-11 22:24 UTC, jessebrennan commented
Closing in favor of #61

2018-09-11 22:24 UTC, closed without merging