Update home page and menu for Commons/Stage Demos (fixes #44)
BD2KGenomics/dcc-dashboard pull request #60
Opened 2018-09-11 01:02 UTC by coverbeck

* Removed references to content not supported in the commons branch,
such as running workflows, invoicing, etc. Also removed some of the supporting
code for those features, but not all.
* Added Commons/Stage logo
* Removed all menu choices, except Home, Data Browser (renamed from Boardwalk),
and Log in
* Created a bunch of new content for the home page.

This is not intended to be end-all, be-all. A UX designer could and should add a lot more
bells and whistles, but this should generally serve its purpose for October.

### Partial screenshot of home page when auth is required:

![screen shot 2018-09-10 at 5 40 50 pm](https://user-images.githubusercontent.com/1049340/45332059-4a4f6480-b523-11e8-943b-0be8398b43cc.png)

### Screenshot of home page when auth is not required:

![screen shot 2018-09-10 at 5 41 59 pm](https://user-images.githubusercontent.com/1049340/45332072-5a674400-b523-11e8-9e43-c535c569ff74.png)

### Screenshot of bottom of home page for both of the above, since the whole page doesn't fit on my monitor:

![screen shot 2018-09-10 at 5 41 29 pm](https://user-images.githubusercontent.com/1049340/45332097-7cf95d00-b523-11e8-893d-72df4bc653c2.png)

2018-09-12 20:13 UTC, jessebrennan requested changes

2018-09-12 20:13 UTC, jessebrennan commented on app.py
> +        project = os.getenv('PROJECT_NAME', '')
I feel like maybe we already talked about this, but should there be a default name?

2018-09-12 20:13 UTC, jessebrennan commented on app.py
> -        return redirect(url_for('action_service'))
I guess this just removes the link, but not the actual invoicing and action services. Maybe it's out of scope but I wonder if those are still features we should bother to keep around or if they should go too.

2018-09-12 20:13 UTC, jessebrennan commented on templates/base.html
>  						<img src="{{url_for('static', filename='img/logo-ucsc-gi@1x.png')}}" srcset="{{url_for('static', filename='img/logo-ucsc-gi@2x.png')}} 2x, {{url_for('static', filename='img/logo-ucsc-gi@3x.png'
This is a nit, and isn't you obviously, but I'd prefer if this like was wrapped at something a little more legible.

2018-09-12 20:13 UTC, jessebrennan commented on templates/index.html
> +    <main class="layout-column layout-padding flex">
Thanks for making the indent / wrapping more sensible :relieved:

2018-09-12 20:20 UTC, coverbeck commented on app.py
> -        return redirect(url_for('action_service'))
They should eventually go too. If we need to restore them, we can go into the Git history.

I actually started to remove the other stuff as part of this, but then I went too far, removing at least one file too many, and decided to back off to limit the scope of the change and not risk breaking anything.

2018-09-12 20:29 UTC, coverbeck commented on app.py
> +        project = os.getenv('PROJECT_NAME', '')
I will dodge the question by removing the line. :) At one point, I was using the project name in the HTML, but then I just ended up writing fairly generic content and I'm not using it at all, so your comment made me realize I can get rid of this.

2018-09-12 20:32 UTC, coverbeck commented on templates/base.html
>  						<img src="{{url_for('static', filename='img/logo-ucsc-gi@1x.png')}}" srcset="{{url_for('static', filename='img/logo-ucsc-gi@2x.png')}} 2x, {{url_for('static', filename='img/logo-ucsc-gi@3x.png'
👍

2018-09-12 20:33 UTC, coverbeck commented on templates/index.html
> +    <main class="layout-column layout-padding flex">
👍

2018-09-12 23:42 UTC, jessebrennan requested changes
Sorry I neglected to review this part before, failing to realize that this was the bulk of what you fixed :grimacing:

2018-09-12 23:42 UTC, jessebrennan commented on templates/index.html
> +                the data's metadata, as well as links to the actual data.
~The data~ **This** includes ~the data's~ metadata ~, as well as~ **and** links to the actual data.

just a suggestion, but the repetitive of 'data' felt a little awkward to me.

2018-09-12 23:42 UTC, jessebrennan commented on templates/index.html
> +                        href="mailto:{{ contact_email }}">{{ contact_email }}</a>.
So if the email is not redacted here, should it not be redacted in the other place?

2018-09-12 23:42 UTC, jessebrennan commented on templates/index.html
> +            those used here as examples,
nitpick but the indentation gets kind of funky here.

2018-09-12 23:42 UTC, jessebrennan commented on templates/index.html
> +                facets, such as <span class="italic">Specimen Type</span>, you
You're surely more up to date on html conventions than I am, but why not use the <i> tag? Has it been deprecated?

2018-09-13 00:49 UTC, coverbeck commented on templates/index.html
> +                the data's metadata, as well as links to the actual data.
Agreed, thanks. Fixed in next push

2018-09-13 00:51 UTC, coverbeck commented on templates/index.html
> +                        href="mailto:{{ contact_email }}">{{ contact_email }}</a>.
This one we need the full email, so that users can send emails to it. I suppose we could redact the display part, but bots would be scanning the href anyway, so I think we should keep it.

I have another ticket to get a group type email address, so that we don't have to display a personal email address here.

2018-09-13 01:01 UTC, coverbeck commented on templates/index.html
> +                facets, such as <span class="italic">Specimen Type</span>, you
Did you mean use the `<i>` tag? I think it got interpreted as literal HTML in your comment. :)

Yes, the `<i> and <b>` tags were considered mistakes, I believe. They mix content with presentation. HTML should be representable as voice, for the visually impaired, and having a tag says italicize makes no sense. Researching my answer, I could use `<em>`, which means emphasize, and whose presentation is italics, but since it's already there, I'd prefer to leave it.

2018-09-13 01:13 UTC, coverbeck commented on templates/index.html
> +                facets, such as <span class="italic">Specimen Type</span>, you
That said, I probably should have picked a better name than italic for the class... Shoots down my whole argument for text to speech. :)

I tried `<em>`, but the default styles for this repo don't have it doing anything, so I'll change it to `emphasis`.

2018-09-13 19:21 UTC, cricketsloan commented
I think that this is fulfilling the tasks at hand.  We can leave config to Dave Rogers.

I think we should use cgl@ucsc.edu for the email for now.  I still do't know where it goes, but in theory I am supposed to be the owner.

2018-09-13 19:23 UTC, cricketsloan commented
Ideally in the future I would like to see a diagram describing our tool set.  But your list of Boardwalk, Azul, etc  is sufficient if not pretty.   I will try to keep this in mind for Dave Rogers

2018-09-13 19:33 UTC, cricketsloan approved these changes
I think that we should use cgl@ucsc.edu.  If you can change the address, this does not need to come back to me for review.  Jesse caught the couple of concerns I had

2018-09-13 22:04 UTC, jessebrennan approved these changes

2018-09-13 22:07 UTC, merged