And /me and /authorization endpoints
BD2KGenomics/dcc-dashboard pull request #61
Opened 2018-09-11 22:24 UTC by jessebrennan

This is an extension of #59.

Both #50 and #52 are covered in this PR because there was going to be some code overlap.

These changes are currently deployed at jesse.ucsc-cgp-dev.org

There were a couple outstanding issues that @coverbeck and I were discussing.

1. One is the access token in the /me endpoint. This is now removed.
2. Another was https://github.com/DataBiosphere/cgp-dashboard/compare/feature/commons...feature/51-auth-endpoint?expand=1#diff-3f41e546893dc64b71aaacad12cad815R357 
   I was wondering if comment is along the lines of what you were thinking.

2018-09-11 23:13 UTC, coverbeck requested changes
Some of this is stylistic -- feel free to disagree with.

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +whitelist_checker = Bouncer(os.getenv('EMAIL_WHITELIST_NAME'))
Will Bouncer handle getting `None` as a parameter?

2018-09-11 23:13 UTC, coverbeck commented on app.py
>      resp = oauth.refresh_token(Auth.TOKEN_URI, refresh_token=refresh_token, **extra)
I would like to see a comment here, that this line will raise the OAuth2Error. Either instead of or as well as your comment at the top. With just the comment at the top, it's not clear exactly where the error might get thrown, nor why you're not checking on line 273 that this line may have failed.

This is fairly nit-picky and personal taste, so feel free to ignore if you disagree.

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +    assert resp.status_code == 200, str(resp.text)
I just read up on `assert` at https://stackoverflow.com/questions/5142418/what-is-the-use-of-assert-in-python, it being new to me in Python. According to that page, you can compile Python to ignore assert statements, so I'm wondering if you should handle this case without using assert?

Your call...

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +    should be sent back in the session cookie.
`will be sent back`

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +        return '', 200
You should return 204 here, like you do on line 446.

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +    output = dict((k, user_data[k]) for k in ('name', 'email'))
You need to check if user is still on whitelist

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +    if not os.getenv('EMAIL_WHITELIST_NAME'):
Instead of checking the env variable, then using the whitelist_checker, which means you have to guard against all uses of whitelist_checker by checking a different variable, maybe you could only set whitelist_checker if the variable is set at the top of the file, and then only check if whitelist_checker is set or not.

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +    If there is no whitelist, return 200
204

2018-09-11 23:13 UTC, coverbeck commented on app.py
> +            if os.getenv('EMAIL_WHITELIST_NAME') and not whitelist_checker.is_authorized(email):
See suggestions about just using one variable -- I would prefer something like the following (excuse any syntax errors), which seems clearer:

```
if whitelist_checker is not None and not whitelist_checker.is_authorized(email):
```

2018-09-11 23:16 UTC, jessebrennan commented on app.py
> +whitelist_checker = Bouncer(os.getenv('EMAIL_WHITELIST_NAME'))
Yes. The only problem with doing it this way is that future devs need to remember to check `EMAIL_WHITELIST_NAME` before making a call to Bouncer. Probably not a big deal.

2018-09-11 23:16 UTC, jessebrennan commented on app.py
>      resp = oauth.refresh_token(Auth.TOKEN_URI, refresh_token=refresh_token, **extra)
I'll add another comment. I don't think they ever hurt.

2018-09-11 23:23 UTC, jessebrennan commented on app.py
> +    assert resp.status_code == 200, str(resp.text)
Yeah i personally don't like using asserts this way, I was just following precedence in other parts of the code. I'll change this one, and maybe a larger refactor / clean up can wait?

2018-09-11 23:25 UTC, coverbeck commented on app.py
> +    assert resp.status_code == 200, str(resp.text)
Sounds good.

2018-09-11 23:26 UTC, jessebrennan commented on app.py
> +        return '', 200
See step 1 here https://github.com/DataBiosphere/cgp-dashboard/issues/52

If I should add a comment that makes me clear lmk.

2018-09-11 23:27 UTC, jessebrennan commented on app.py
> +    If there is no whitelist, return 200
https://github.com/DataBiosphere/cgp-dashboard/issues/52 see step 1

2018-09-11 23:29 UTC, coverbeck commented on app.py
> +        return '', 200
My bad on the original description in the issue... So I'm correcting myself. :)

If there is no content, which there isn't in this case, you're supposed to return 204, not 200.

2018-09-11 23:32 UTC, jessebrennan commented on app.py
> +            if os.getenv('EMAIL_WHITELIST_NAME') and not whitelist_checker.is_authorized(email):
The closest thing to what you're describing would be

```
if whitelist_checker.secret_name is not None and not whitelist_checker.is_authorized(email):
```

But I think the current way is more clear than this. Do you disagree?

2018-09-11 23:38 UTC, jessebrennan commented on app.py
> +    output = dict((k, user_data[k]) for k in ('name', 'email'))
Whoops! duh...

2018-09-11 23:39 UTC, jessebrennan commented on app.py
> +    if not os.getenv('EMAIL_WHITELIST_NAME'):
Ok, sure!

2018-09-11 23:39 UTC, jessebrennan commented on app.py
> +            if os.getenv('EMAIL_WHITELIST_NAME') and not whitelist_checker.is_authorized(email):
Nevermind, I see how this is connected to your previous comment

2018-09-11 23:50 UTC, coverbeck commented on app.py
> +            if os.getenv('EMAIL_WHITELIST_NAME') and not whitelist_checker.is_authorized(email):
I would not even initialize whitelist_checker itself if the environment variable is not set, and then do it like I suggested. 

My feeling is it is more straightforward to check if whitelist_checker is set and then use it if it is, vs. you checking an environment variable that you have to know the whitelist_checker has a dependency on and then using the whitelist_checker based on that. On top of that, you are creating an instance of the whitelist_checker when you don't really need it.

But this is getting really detailed for a very small thing and not worth it, so if you still disagree, I'm good with you doing it the current way.

2018-09-12 18:56 UTC, coverbeck requested changes
One silly comment, one real thing, and one thing I think, but I'm not sure, that you have to address.

2018-09-12 18:56 UTC, coverbeck commented on app.py
> +    # this call may throw an OAuth2Error
`Throw` sounds like Java, which I'm used to... :) Should be `raise` in Python? It's fine though.

2018-09-12 18:56 UTC, coverbeck commented on app.py
> +        # token expired, try once more
If token is not None, then they sent an Authorization header with the token... In that case, I think you should stop here -- not try to refresh the token, since you shouldn't have a refresh token anyway, nor do the session.pop stuff, because they've explicitly specified auth, so it shouldn't have the side effect of updating auth cookie values.

I suppose a user could have set the Authorization header AND have the cookie with refresh and access tokens, but it's unlikely, and if they do, I don't think we should mix the Auth header interpretation with the cookie values, if that make sense.

2018-09-12 18:56 UTC, coverbeck commented on app.py
> +    if not whitelist_checker.is_authorized(user_data['email']):
Do you need to check that whitelist_checker is not None?

2018-09-12 19:18 UTC, jessebrennan commented on app.py
> +    # this call may throw an OAuth2Error
I don't think anyone will misunderstand

2018-09-12 19:38 UTC, jessebrennan commented on app.py
> +    if not whitelist_checker.is_authorized(user_data['email']):
Yes. Thanks!

2018-09-12 19:40 UTC, jessebrennan commented on app.py
> +        # token expired, try once more
That makes sense. I only did it this way because I interpreted the docs to imply this. I'll change it now.

2018-09-12 20:08 UTC, coverbeck approved these changes
👍

2018-09-12 20:19 UTC, merged