Return either user info or anon user (resolves #66)
BD2KGenomics/dcc-dashboard pull request #71
Opened 2018-09-21 23:50 UTC by jessebrennan

This makes a cleaner interface for boardwalk.

This is currently deployed at jesse.ucsc-cgp-dev.org and Dave Rogers approves

2018-09-22 00:15 UTC, coverbeck approved these changes
I'm ambivalent about this... If you're logged in but not whitelisted, but we're going to indicate you're anonymous, even though we know who you are.

I'll go ahead and approve with reservations. Plus see my one comment, where you don't seem to be consistently returning anonymous.

2018-09-22 00:15 UTC, coverbeck commented on app.py
> -    except OAuth2Error as e:
What about line above this one (can't comment on it, since you didn't change it, an annoying GitHub feature)? Do you want to return the anonymous user in that case?

2018-09-22 00:21 UTC, jessebrennan commented on app.py
> -    except OAuth2Error as e:
Yes I fixed that locally but haven't pushed yet. Good catch.

2018-09-22 00:23 UTC, jessebrennan commented
> I'm ambivalent about this... If you're logged in but not whitelisted, but we're going to indicate you're anonymous, even though we know who you are.

Maybe we should get a second opinion from Dave before merging. We didn't discuss the detail so it would be worth confirming his opinion.

2018-09-22 00:28 UTC, coverbeck commented
Pinged on Slack as well, but @NoopDog , but in the case of an non-whitelisted user, why do you want `\me` to return anonymous user when we know who you are?

2018-09-22 00:42 UTC, coverbeck requested changes
Per Slack discussion in cc-boardwalk, authenticated but not authorized should return the user, not anonymous.

2018-09-24 18:19 UTC, jessebrennan commented
@coverbeck fixed.

2018-09-24 19:31 UTC, coverbeck approved these changes

2018-09-24 19:35 UTC, merged