Add logger messages to log user access to the CGP platform
BD2KGenomics/dcc-dashboard pull request #82
Opened 2018-10-10 05:29 UTC by wshands

Added appropriate logging to the `cgp-dashboard` service (our current auth service) to log attempted user access to the platform
Fixes TLP 654

2018-10-10 18:24 UTC, coverbeck requested changes

2018-10-10 18:24 UTC, coverbeck commented on app.py
> +        user_info = ", ".join("=".join((str(k),str(v))) for k,v in user_data.items())
This will log the refresh and access tokens, which we shouldn't do.

2018-10-10 18:24 UTC, coverbeck commented on app.py
> +        user_info = ", ".join("=".join((str(k),str(v))) for k,v in user_data.items())
This is a duplicate of line 450; if you change line 450 to exclude the tokens, you should probably extract this to a function.

2018-10-10 18:24 UTC, coverbeck commented on app.py
> +    user_info = ", ".join("=".join((str(k),str(v))) for k,v in user_data.items())
Same as comment for line 450

2018-10-10 18:24 UTC, coverbeck commented on app.py
> +        app.logger.info('Current user with attribtues %s is authenticated; redirecting to index URL', str(current_user))
This and all the other `str(current_user)` will log the tokens, which we should not do.

2018-10-10 20:44 UTC, coverbeck requested changes

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +app.debug = True
Should this be hard-coded like this? What does this do?

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +        app.logger.info('Request by user anonymous')
I don't think it serves any purpose to log this by default. I would change this to `app.logger.debug...`

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +        app.logger.info('Request by user anonymous')
Would change to debug

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +        app.logger.info('No whitelist; user is authorized')
I would change this to debug

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +        app.logger.info('Could not fetch information for current user')
I would make this .error

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +            app.logger.info('Could not verify token for current user with ID %s', current_user.get_id())
I would make this .error

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +            app.logger.info('Current user with ID %s access is denied', current_user.get_id())
I don't know that you can rely on current_user not being None, but I'm not sure.

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +        app.logger.info('Redirecting current user with ID %s to login URL', current_user.get_id())
I don't know that you can rely on current_user not being None, but I'm not sure.

2018-10-10 20:44 UTC, coverbeck commented on app.py
> +            app.logger.info('Could not fetch token for current user with ID %s', current_user.get_id())
I don't know that you can rely on current_user not being None, but I'm not sure.

2018-10-10 21:03 UTC, mikebaumann commented on app.py
> +app.debug = True
I asked @wshands to put this in temporarily so he could see, and continue work on, adding his INFO level messages. This has now been replaced with a more appropriate (IMO) workaround for Flask's logging configuration.

2018-10-10 21:10 UTC, mikebaumann commented on app.py
> +        app.logger.info('Request by user anonymous')
I am inclined to think the exception should be logged, and the message left at info level.
Something like:

```
    except (ValueError, OAuth2Error) as e:
        app.logger.info('Failed to get user info: %s', str(e)
        return jsonify({'name': 'anonymous'})
```

2018-10-10 21:12 UTC, coverbeck commented on app.py
> +        app.logger.info('Request by user anonymous')
You're right, I was overzealous, although I would make it `app.logger.error`.

2018-10-10 21:16 UTC, mikebaumann commented on app.py
> +    app.logger.info('Request by user with email %s', user_data['email'])
Do the messages currently being logged identify the endpoint/operation you are in?
If so, great. If not, it probably needs to be incorporated into the message.
Simply seeing an entry in the CloudWatch logs like:
```
Request by user with email ...
```
In itself gives the viewer no idea about what operation was being performed and is of very limited usefulness in itself.

2018-10-10 21:16 UTC, mikebaumann commented on app.py
> +        app.logger.info('No whitelist; user is authorized')
Agreed.

2018-10-10 21:19 UTC, mikebaumann commented on app.py
> +        app.logger.info('Current user with ID %s is authenticated; redirecting to index URL', current_user.get_id())
Consider making the messages more concise, less verbose.
For example, instead of:
```
Current user with ID %s is authenticated; redirecting to index URL
```
consider:
```
User %s is authenticated; redirecting to index URL'
```

2018-10-10 21:27 UTC, mikebaumann commented on app.py
> +        app.logger.info('Redirecting current user with ID %s to login URL', current_user.get_id())
Correct, I recall seeing messages logged in which the user id was `None`. I think that is helpful. If we knew the value would always be `None`, I'd be happy to that value out, yet I don't currently know that.

2018-10-10 21:28 UTC, mikebaumann commented on app.py
> +            app.logger.info('Could not verify token for current user with ID %s', current_user.get_id())
Agreed.

2018-10-10 21:57 UTC, wshands commented
Request path added to logger messages

2018-10-10 21:58 UTC, wshands commented on app.py
> +        app.logger.info('Could not fetch information for current user')
Done

2018-10-10 23:25 UTC, coverbeck requested changes

2018-10-10 23:25 UTC, coverbeck commented on app.py
> +        app.logger.debug('Request path %s by user anonymous', request.path)
1. Per @mikebaumann, which makes sense to me, this should be `app.logger.error`.
2. This is not an anonymous user, this is a user that we had some sort of trouble verify. I know the subsequent statement implies otherwise, but we decided for the UI that this endpoint would always return a 200, so if we weren't able to determine the user, we would just return anonymous. Line 408 is when we know the user actually is anonymous.

2018-10-10 23:25 UTC, coverbeck commented on app.py
> +                app.logger.info('Request path %s. Current user with ID %s access is denied', request.path, current_user.get_id())
Should be .error

2018-10-10 23:25 UTC, coverbeck commented on app.py
> +                app.logger.info('Request path %s. Access is denied for current user None', request.path)
Should be .error

2018-10-10 23:25 UTC, coverbeck commented on app.py
> +        app.logger.info('Could not fetch information for current user')
Still shows up as info, not error.

2018-10-11 00:40 UTC, coverbeck approved these changes

2018-10-11 00:41 UTC, merged