Removed if condition, and left text for controlled-access data
BD2KGenomics/dcc-dashboard pull request #93
Opened 2018-11-08 23:53 UTC by mjkrause

2018-11-09 15:57 UTC, mjkrause commented
@coverbeck, you can see that change at https://mkrause6.ucsc-cgp-dev.org.

2018-11-09 16:54 UTC, coverbeck requested changes

2018-11-09 16:54 UTC, coverbeck commented on templates/index.html
> +            <h3 class="center">Restricted Access Data</h3>
This doesn't seem right... The dev deployment will not require you to be whitelisted, it will only require you to be logged in. And that instance does not have restricted access data.

Basically, you still need a version of lines 41-43, although the part where it says you can view it anonymously needs to be modified.

2018-11-10 00:47 UTC, mjkrause commented on templates/index.html
> +            <h3 class="center">Restricted Access Data</h3>
You're right. I've changed the wording to reflect this. Note, the running instance mkrause6.ucsc-cgp-dev.org doesn't show it as I use to work on #91.

2018-11-13 18:48 UTC, coverbeck requested changes

2018-11-13 18:48 UTC, coverbeck commented on templates/index.html
> +            <h3 class="center">Open Access Data</h3>
You need the `if {% if auth_required %}` that you deleted, and the block inside it should remain unchanged. Your changes should go inside the `{% else %}` block.

Regarding the actual text, I would not say `with Google`, as we may someday change the log in to use Auth0 or Fence. You could update the text every time we change the provider, but I think it's easier to say to just log in and not get into the details of what the login implementation is.

I would also say `in order to browse it`, and leave out the `or export it`.

My suggestion would be something like: `You are required to log in order to browse the open access data.`

2018-11-13 18:53 UTC, coverbeck commented on templates/index.html
> +            <h3 class="center">Open Access Data</h3>
The variable name `auth_required` may be part of the confusion, because now we are always requiring auth. Perhaps it would be clearer if you renamed that variable to something like `whitelist_validation_required`, as that is what that block indicates.

2018-11-13 23:42 UTC, mjkrause commented on templates/index.html
> +            <h3 class="center">Open Access Data</h3>
I've put the if-condition back in, and changed the variable name to the one you suggested. Added text accordingly. Haven't tested it it in a running instance as I'm  having problems deploying, which appears to be caused by installing Oracle-Java in the dcc-dasboard-service container.

2018-11-14 18:55 UTC, coverbeck requested changes
One small change...

2018-11-14 18:55 UTC, coverbeck commented on templates/index.html
> +                    link at the top of the page
Missing a period at the end of the sentence. :)

2018-11-15 17:11 UTC, mjkrause commented on templates/index.html
> +                    link at the top of the page
DOne. I also changed the title of this PR.

2018-11-15 17:22 UTC, coverbeck approved these changes

2018-11-15 23:28 UTC, merged